[general]
import = ["tokyonight_night.toml"]

[window]
dimensions = { columns = 100, lines = 30 }
padding = { x = 5, y = 5 }
decorations = "none"
startup_mode = "Windowed"
opacity = 0.50
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0
offset = { x = 0, y = 1 }

[terminal]
osc52 = "OnlyCopy"

[terminal.shell]
program = "/bin/zsh"  # or "/bin/bash", "fish", etc.
args = ["--login", "-i"]  # Forces zsh to run as an interactive login shell

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
blink_interval = 500
unfocused_hollow = true
